"""initial_schema

Revision ID: f0948750e837
Revises: 
Create Date: 2026-09-21 07:08:44.675700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0948750e837'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('movement_pattern', sa.String(length=30), nullable=False),
    sa.Column('equipment', sa.String(length=30), nullable=False),
    sa.Column('exercise_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('bilateral', sa.Boolean(), nullable=False),
    sa.Column('beginner_friendly', sa.Boolean(), nullable=False),
    sa.CheckConstraint("difficulty IN ('beginner', 'intermediate', 'advanced')", name='ck_exercises_difficulty'),
    sa.CheckConstraint("exercise_type IN ('compound', 'isolation')", name='ck_exercises_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fdc_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('serving_description', sa.String(length=100), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbohydrate_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.CheckConstraint('calories >= 0', name='ck_foods_calories'),
    sa.CheckConstraint('carbohydrate_g >= 0', name='ck_foods_carbs'),
    sa.CheckConstraint('fat_g >= 0', name='ck_foods_fat'),
    sa.CheckConstraint('protein_g >= 0', name='ck_foods_protein'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fdc_id')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('muscle_group', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("experience_level IN ('beginner', 'intermediate', 'advanced')", name='ck_users_experience'),
    sa.CheckConstraint("gender IN ('male', 'female')", name='ck_users_gender'),
    sa.CheckConstraint("goal IN ('fat_loss', 'muscle_gain', 'maintenance', 'general_fitness')", name='ck_users_goal'),
    sa.CheckConstraint('age >= 16 AND age <= 100', name='ck_users_age'),
    sa.CheckConstraint('height_cm > 100 AND height_cm < 250', name='ck_users_height'),
    sa.CheckConstraint('training_days_per_week BETWEEN 1 AND 7', name='ck_users_training_days'),
    sa.CheckConstraint('weight_kg > 30 AND weight_kg < 300', name='ck_users_weight'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exercise_muscles',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.CheckConstraint("role IN ('primary', 'secondary')", name='ck_exercise_muscles_role'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id'),
    sa.UniqueConstraint('exercise_id', 'muscle_id', name='uq_exercise_muscle')
    )
    op.create_table('nutrition_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bmr', sa.Float(), nullable=False),
    sa.Column('tdee', sa.Float(), nullable=False),
    sa.Column('calorie_target', sa.Float(), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=False),
    sa.Column('carb_target_g', sa.Float(), nullable=False),
    sa.Column('fat_target_g', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("goal IN ('fat_loss', 'muscle_gain', 'maintenance')", name='ck_nutrition_goal'),
    sa.CheckConstraint('bmr > 0', name='ck_nutrition_bmr'),
    sa.CheckConstraint('calorie_target > 0', name='ck_nutrition_calories'),
    sa.CheckConstraint('protein_target_g > 0', name='ck_nutrition_protein'),
    sa.CheckConstraint('tdee > 0', name='ck_nutrition_tdee'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_available', sa.JSON(), nullable=False),
    sa.Column('preferred_exercises', sa.JSON(), nullable=False),
    sa.Column('disliked_exercises', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('dietary_preferences', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation_reasoning', sa.Text(), nullable=True),
    sa.Column('evidence_sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'archived')", name='ck_workout_plans_status'),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name='ck_workout_plans_days'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nutrition_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('generation_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('meals_per_day BETWEEN 1 AND 8', name='ck_meal_plans_meals_per_day'),
    sa.ForeignKeyConstraint(['nutrition_profile_id'], ['nutrition_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plan_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('focus', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_number', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plan_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_plan_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_in_day', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=False),
    sa.Column('target_reps_max', sa.Integer(), nullable=False),
    sa.Column('target_rir_min', sa.Integer(), nullable=False),
    sa.Column('target_rir_max', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('progression_rule', sa.String(length=60), nullable=False),
    sa.Column('exercise_reasoning', sa.Text(), nullable=True),
    sa.CheckConstraint('target_reps_min <= target_reps_max', name='ck_wpe_reps'),
    sa.CheckConstraint('target_rir_min <= target_rir_max', name='ck_wpe_rir'),
    sa.CheckConstraint('target_rir_min >= 0 AND target_rir_max <= 5', name='ck_wpe_rir_range'),
    sa.CheckConstraint('target_sets > 0', name='ck_wpe_sets'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_plan_day_id'], ['workout_plan_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_day_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('overall_rpe', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('overall_rpe IS NULL OR (overall_rpe BETWEEN 1 AND 10)', name='ck_sessions_rpe'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_day_id'], ['workout_plan_days.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('reps > 0', name='ck_logs_reps'),
    sa.CheckConstraint('rir IS NULL OR (rir BETWEEN 0 AND 10)', name='ck_logs_rir'),
    sa.CheckConstraint('rpe IS NULL OR (rpe BETWEEN 1 AND 10)', name='ck_logs_rpe'),
    sa.CheckConstraint('set_number > 0', name='ck_logs_set_number'),
    sa.CheckConstraint('weight_kg >= 0', name='ck_logs_weight'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_plan_meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.CheckConstraint('calories >= 0', name='ck_meal_items_calories'),
    sa.CheckConstraint('quantity_g > 0', name='ck_meal_items_quantity'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_plan_meal_id'], ['meal_plan_meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_items')
    op.drop_table('exercise_logs')
    op.drop_table('workout_sessions')
    op.drop_table('workout_plan_exercises')
    op.drop_table('meal_plan_meals')
    op.drop_table('workout_plan_days')
    op.drop_table('meal_plans')
    op.drop_table('workout_plans')
    op.drop_table('user_preferences')
    op.drop_table('nutrition_profiles')
    op.drop_table('exercise_muscles')
    op.drop_table('users')
    op.drop_table('muscles')
    op.drop_table('foods')
    op.drop_table('exercises')
    # ### end Alembic commands ###
