"""
Workout-related ORM models: plans, days, exercises, sessions, and logs.

Schema hierarchy:
  WorkoutPlan
    └── WorkoutPlanDay (e.g. "Upper A", "Lower B")
          └── WorkoutPlanExercise (e.g. Bench Press: 3×8-12, RIR 2)

  WorkoutSession (one actual gym visit)
    └── ExerciseLog (one exercise in that session)
          └── Individual sets are rows in ExerciseLog with set_number

Design decisions:
- Each set is a separate ExerciseLog row (not a JSON array of sets).
  This enables precise per-set volume/intensity queries in SQL.
- is_warmup flag is critical: volume calculations ONLY count is_warmup=False rows.
- evidence_sources on WorkoutPlan is JSONB — stores citation_ids used when
  the agent generated the plan. Enables full traceability from plan → evidence.
- progression_rule is a plain string key (e.g. "double_progression_8_12")
  that maps to logic in training_engine.py. Keeps DB simple, logic in code.
"""

from datetime import date, datetime, timezone

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base, TimestampMixin


class WorkoutPlan(Base, TimestampMixin):
    """
    A complete training program for a user.
    Generated by the agent; stores why it was created and what evidence was used.
    """

    __tablename__ = "workout_plans"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    goal: Mapped[str] = mapped_column(String(30), nullable=False)
    days_per_week: Mapped[int] = mapped_column(nullable=False)

    # "active" | "completed" | "archived"
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")

    # Agent reasoning: why was this plan created? (free text, stored for transparency)
    generation_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Citation IDs used when generating this plan.
    # Example: ["SCHOENFELD-2017", "ACSM-2009"]
    # This is what makes every plan traceable back to evidence.
    evidence_sources: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'completed', 'archived')",
            name="ck_workout_plans_status",
        ),
        CheckConstraint(
            "days_per_week BETWEEN 1 AND 7",
            name="ck_workout_plans_days",
        ),
    )

    # ── Relationships ────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship(back_populates="workout_plans")  # noqa: F821
    days: Mapped[list["WorkoutPlanDay"]] = relationship(
        back_populates="plan", cascade="all, delete-orphan", order_by="WorkoutPlanDay.day_number"
    )

    def __repr__(self) -> str:
        return f"<WorkoutPlan id={self.id} name={self.name!r} status={self.status!r}>"


class WorkoutPlanDay(Base):
    """
    One training day within a plan (e.g. Day 1 = "Upper A").
    """

    __tablename__ = "workout_plan_days"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    workout_plan_id: Mapped[int] = mapped_column(
        ForeignKey("workout_plans.id", ondelete="CASCADE"), nullable=False
    )
    day_number: Mapped[int] = mapped_column(nullable=False)  # 1-7
    name: Mapped[str] = mapped_column(String(60), nullable=False)  # e.g. "Upper A"

    # "push" | "pull" | "legs" | "upper" | "lower" | "full_body"
    focus: Mapped[str] = mapped_column(String(30), nullable=False)

    # ── Relationships ────────────────────────────────────────────────────────
    plan: Mapped["WorkoutPlan"] = relationship(back_populates="days")
    exercises: Mapped[list["WorkoutPlanExercise"]] = relationship(
        back_populates="day", cascade="all, delete-orphan", order_by="WorkoutPlanExercise.order_in_day"
    )
    sessions: Mapped[list["WorkoutSession"]] = relationship(back_populates="plan_day")

    def __repr__(self) -> str:
        return f"<WorkoutPlanDay id={self.id} day={self.day_number} name={self.name!r}>"


class WorkoutPlanExercise(Base):
    """
    An exercise prescription within a plan day.

    Stores the target sets, rep range, RIR range, rest, and progression rule.
    The agent also stores its reasoning for why this exercise was chosen.
    """

    __tablename__ = "workout_plan_exercises"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    workout_plan_day_id: Mapped[int] = mapped_column(
        ForeignKey("workout_plan_days.id", ondelete="CASCADE"), nullable=False
    )
    exercise_id: Mapped[int] = mapped_column(
        ForeignKey("exercises.id", ondelete="RESTRICT"), nullable=False
    )
    order_in_day: Mapped[int] = mapped_column(nullable=False)  # 1 = first exercise

    # Prescription
    target_sets: Mapped[int] = mapped_column(nullable=False)
    target_reps_min: Mapped[int] = mapped_column(nullable=False)
    target_reps_max: Mapped[int] = mapped_column(nullable=False)
    target_rir_min: Mapped[int] = mapped_column(nullable=False, default=1)
    target_rir_max: Mapped[int] = mapped_column(nullable=False, default=3)
    rest_seconds: Mapped[int] = mapped_column(nullable=False, default=120)

    # Key: maps to a progression algorithm in training_engine.py
    # e.g. "double_progression_8_12", "linear_load_5x5"
    progression_rule: Mapped[str] = mapped_column(String(60), nullable=False, default="double_progression")

    # Why did the agent choose this exercise?
    exercise_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint("target_sets > 0", name="ck_wpe_sets"),
        CheckConstraint("target_reps_min <= target_reps_max", name="ck_wpe_reps"),
        CheckConstraint("target_rir_min <= target_rir_max", name="ck_wpe_rir"),
        CheckConstraint("target_rir_min >= 0 AND target_rir_max <= 5", name="ck_wpe_rir_range"),
    )

    # ── Relationships ────────────────────────────────────────────────────────
    day: Mapped["WorkoutPlanDay"] = relationship(back_populates="exercises")
    exercise: Mapped["Exercise"] = relationship(back_populates="workout_plan_exercises")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<WorkoutPlanExercise exercise_id={self.exercise_id} "
            f"sets={self.target_sets} reps={self.target_reps_min}-{self.target_reps_max}>"
        )


class WorkoutSession(Base, TimestampMixin):
    """
    One actual gym visit — what the user did on a specific date.

    Optionally linked to a WorkoutPlanDay (nullable: user may log
    sessions outside of their plan, e.g. an unplanned workout).
    """

    __tablename__ = "workout_sessions"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    workout_plan_day_id: Mapped[int | None] = mapped_column(
        ForeignKey("workout_plan_days.id", ondelete="SET NULL"), nullable=True
    )
    session_date: Mapped[date] = mapped_column(Date, nullable=False)
    duration_minutes: Mapped[int | None] = mapped_column(nullable=True)

    # Overall session RPE (1-10): how hard did the whole session feel?
    overall_rpe: Mapped[int | None] = mapped_column(nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "overall_rpe IS NULL OR (overall_rpe BETWEEN 1 AND 10)",
            name="ck_sessions_rpe",
        ),
    )

    # ── Relationships ────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship(back_populates="workout_sessions")  # noqa: F821
    plan_day: Mapped["WorkoutPlanDay | None"] = relationship(back_populates="sessions")
    exercise_logs: Mapped[list["ExerciseLog"]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<WorkoutSession id={self.id} date={self.session_date} user_id={self.user_id}>"


class ExerciseLog(Base):
    """
    One set of one exercise within a WorkoutSession.

    Each row = one set. This enables:
    - Precise volume counting (sum of non-warmup sets)
    - Per-set RIR tracking (was this set harder than prescribed?)
    - Progression checks (did reps increase across sessions?)

    is_warmup=True rows are EXCLUDED from all volume calculations.
    """

    __tablename__ = "exercise_logs"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    workout_session_id: Mapped[int] = mapped_column(
        ForeignKey("workout_sessions.id", ondelete="CASCADE"), nullable=False
    )
    exercise_id: Mapped[int] = mapped_column(
        ForeignKey("exercises.id", ondelete="RESTRICT"), nullable=False
    )
    set_number: Mapped[int] = mapped_column(nullable=False)  # 1, 2, 3...
    weight_kg: Mapped[float] = mapped_column(nullable=False)
    reps: Mapped[int] = mapped_column(nullable=False)

    # RIR (Reps In Reserve): how many reps short of failure?
    # Null = user didn't track RIR for this set
    rir: Mapped[int | None] = mapped_column(nullable=True)

    # RPE (Rate of Perceived Exertion, 1-10 scale)
    # Optional alternative/complement to RIR
    rpe: Mapped[int | None] = mapped_column(nullable=True)

    # Critical: warm-up sets are excluded from volume counts
    is_warmup: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint("weight_kg >= 0", name="ck_logs_weight"),
        CheckConstraint("reps > 0", name="ck_logs_reps"),
        CheckConstraint("rir IS NULL OR (rir BETWEEN 0 AND 10)", name="ck_logs_rir"),
        CheckConstraint("rpe IS NULL OR (rpe BETWEEN 1 AND 10)", name="ck_logs_rpe"),
        CheckConstraint("set_number > 0", name="ck_logs_set_number"),
    )

    # ── Relationships ────────────────────────────────────────────────────────
    session: Mapped["WorkoutSession"] = relationship(back_populates="exercise_logs")
    exercise: Mapped["Exercise"] = relationship(back_populates="exercise_logs")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<ExerciseLog exercise_id={self.exercise_id} "
            f"set={self.set_number} {self.weight_kg}kg×{self.reps} RIR={self.rir}>"
        )
